nutrilab/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('autenticacao.urls')),
    path('', include('plataforma.urls')),
]
## Adiciona a URL para os arquivos de media
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

plataforma/urls.py
from django.urls import path
from . import views


app_name = 'plataforma'

urlpatterns = [
    path('pacientes/', views.pacientes, name='pacientes'),
    path('dados_paciente/', views.dados_paciente_listar, name='dados_paciente_listar'),
    path('dados_paciente/<str:id>/', views.dados_paciente, name='dados_paciente'),
    path('grafico_peso/<str:id>/', views.grafico_peso, name='grafico_peso'),
    path('plano_alimentar_listar/', views.plano_alimentar_listar, name='plano_alimentar_listar'),
    path('plano_alimentar/<str:id>', views.plano_alimentar, name='plano_alimentar'),
    path('refeicao/<str:id_paciente>', views.refeicao, name='refeicao'),
    path('opcao/<str:id_paciente>', views.opcao, name='opcao'),
]

plataforma/models.py
from django.db import models
from django.contrib.auth.models import User

class Pacientes(models.Model):
    choices_sexo = (('F', 'Feminino'),
                    ('M', 'Masculino'))
    nome = models.CharField(max_length=50)
    sexo = models.CharField(max_length=1, choices=choices_sexo)
    idade = models.IntegerField()
    email = models.EmailField()
    telefone = models.CharField(max_length=19)
    nutri = models.ForeignKey(User, on_delete=models.CASCADE)  ## Se o nutricionista for excluído do banco de dados, seus pacientes tbm serão

    def __str__(self):
        return self.nome


class DadosPaciente(models.Model):
    paciente = models.ForeignKey(Pacientes, on_delete=models.CASCADE)
    data = models.DateTimeField()
    peso = models.IntegerField()
    altura = models.IntegerField()
    percentual_gordura = models.IntegerField()
    percentual_musculo = models.IntegerField()
    colesterol_hdl = models.IntegerField()
    colesterol_ldl = models.IntegerField()
    colesterol_total = models.IntegerField()
    trigliceridios = models.IntegerField()
    

    def __str__(self):
        return f"Paciente({self.paciente.nome}, {self.peso})"
    

class Refeicao(models.Model):
    paciente = models.ForeignKey(Pacientes, on_delete=models.CASCADE)
    titulo = models.CharField(max_length=50)
    horario = models.TimeField()
    carboidratos = models.IntegerField()
    proteinas = models.IntegerField()
    gorduras = models.IntegerField()

    def __str__(self):
        return self.titulo


class Opcao(models.Model):
    refeicao = models.ForeignKey(Refeicao, on_delete=models.CASCADE)
    imagem = models.ImageField(upload_to="opcao")
    descricao = models.TextField()  ## Sem limite de caracteres

    def __str__(self):
        return self.descricao

plataforma/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, Http404, JsonResponse
from django.contrib import messages
from django.contrib.messages import constants
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt

from .models import Pacientes, DadosPaciente, Refeicao, Opcao

from datetime import datetime

@login_required(login_url='/auth/logar')
def pacientes(request):
    if request.method == 'GET':
        pacientes = Pacientes.objects.filter(nutri=request.user)
        return render(request, 'pacientes.html', {'pacientes': pacientes})
    elif request.method == 'POST':
        nome = request.POST.get('nome')
        sexo = request.POST.get('sexo')
        idade = request.POST.get('idade')
        email = request.POST.get('email')
        telefone = request.POST.get('telefone')

        if (len(nome.strip()) == 0) or (len(sexo.strip()) == 0) or (len(idade.strip()) == 0) or (len(email.strip()) == 0) or (len(telefone.strip()) == 0):
            messages.add_message(request, constants.ERROR, 'Preencha todos os campos')
            return redirect('/pacientes/')

        if not idade.isnumeric():
            messages.add_message(request, constants.ERROR, 'Digite uma idade válida')
            return redirect('/pacientes/')

        pacientes = Pacientes.objects.filter(email=email)

        if pacientes.exists():
            messages.add_message(request, constants.ERROR, 'Já existe um paciente com esse E-mail')
            return redirect('/pacientes/')

        try:
            paciente = Pacientes(
                nome=nome,
                sexo=sexo,
                idade=idade,
                email=email,
                telefone=telefone,
                nutri=request.user,
            )
            paciente.save()
            messages.add_message(request, constants.SUCCESS, 'Paciente cadastrado com sucesso')
        except:
            messages.add_message(request, constants.ERROR, 'Erro interno do sistema')
        finally:
            return redirect('/pacientes/')


@login_required(login_url='/auth/logar')
def dados_paciente_listar(request):
    if request.method == 'GET':
        pacientes = Pacientes.objects.filter(nutri=request.user)
        return render(request, 'dados_paciente_listar.html', {'pacientes': pacientes})
    

@login_required(login_url='/auth/logar')
def dados_paciente(request, id):
    try:
        paciente = get_object_or_404(Pacientes, id=id) ## Verifica se esse paciente existe. Caso contrário retorna una página 404
    except Http404:
        messages.add_message(request, constants.ERROR, f'Paciente com o ID {id} não está cadastrado')
        return redirect('/dados_paciente/')   
    else:    ## somente será efetuado caso o try for bem-sucedido
        if not paciente.nutri == request.user:  ## Verifica se o paciente é do usuário (nutricionista) que está logado
            messages.add_message(request, constants.ERROR, 'Não é possível acessar os pacientes de outro usuário.')
            return redirect('/dados_paciente/')
        if request.method == 'GET':
            dados_paciente = DadosPaciente.objects.filter(paciente=paciente)
            return render(request, 'dados_paciente.html', {'paciente': paciente, 'dados_paciente': dados_paciente})
        elif request.method == "POST":
            # TODO: realizar as validações para preenchimento dos campos corretamente
            peso = request.POST.get('peso')
            altura = request.POST.get('altura')
            gordura = request.POST.get('gordura')
            musculo = request.POST.get('musculo')

            hdl = request.POST.get('hdl')
            ldl = request.POST.get('ldl')
            colesterol_total = request.POST.get('ctotal')
            triglicerídios = request.POST.get('triglicerídios')

            paciente = DadosPaciente(paciente=paciente,
                                data=datetime.now(),
                                peso=peso,
                                altura=altura,
                                percentual_gordura=gordura,
                                percentual_musculo=musculo,
                                colesterol_hdl=hdl,
                                colesterol_ldl=ldl,
                                colesterol_total=colesterol_total,
                                trigliceridios=triglicerídios)

            paciente.save()

            messages.add_message(request, constants.SUCCESS, 'Dados cadastrado com sucesso')

            return redirect('/dados_paciente/')
        

@login_required(login_url='/auth/logar')
@csrf_exempt  ## Desativa a verificação CSRF (Cross-Site Request Forgery) / usamos quando um serviço externo não inclui automaticamente os cabeçalhos CSRF
def grafico_peso(request, id):
    paciente = Pacientes.objects.get(id=id)
    dados = DadosPaciente.objects.filter(paciente=paciente).order_by('data')

    pesos = [dado.peso for dado in dados]
    labels = list(range(len(pesos)))
    data = {
        'peso': pesos,
        'labels': labels,
    }
    return JsonResponse(data)


def plano_alimentar_listar(request):
    if request.method == "GET":
        pacientes = Pacientes.objects.filter(nutri=request.user)
        return render(request, 'plano_alimentar_listar.html', {'pacientes': pacientes})
    

def plano_alimentar(request, id):
    try:
        paciente = get_object_or_404(Pacientes, id=id) ## Verifica se esse paciente existe. Caso contrário retorna una página 404
    except Http404:
        messages.add_message(request, constants.ERROR, f'Paciente com o ID {id} não está cadastrado')
        return redirect('/dados_paciente/')  
    else:    ## somente será efetuado caso o try for bem-sucedido
        if not paciente.nutri == request.user:  ## Verifica se o paciente é do usuário (nutricionista) que está logado
            messages.add_message(request, constants.ERROR, 'Não é possível acessar os pacientes de outro usuário.')
            return redirect('/dados_paciente/')

        if request.method == "GET":
            refeicoes = Refeicao.objects.filter(paciente=paciente).order_by('horario')
            opcoes = Opcao.objects.all()
            content = {
                'paciente': paciente,
                'refeicoes': refeicoes,
                'opcoes': opcoes,
            }
            return render(request, 'plano_alimentar.html', content)
        

def refeicao(request, id_paciente):
    try:
        paciente = get_object_or_404(Pacientes, id=id_paciente) ## Verifica se esse paciente existe. Caso contrário retorna una página 404
    except Http404: ## Se retornar 404, manda uma mensagem de volta e redireciona
        messages.add_message(request, constants.ERROR, f'Paciente com o ID {id} não está cadastrado')
        return redirect('/dados_paciente/')  
    else:    ## somente será efetuado caso o try for bem-sucedido
        if not paciente.nutri == request.user:  ## Verifica se o paciente é do usuário (nutricionista) que está logado
            messages.add_message(request, constants.ERROR, 'Não é possível acessar os pacientes de outro usuário.')
            return redirect('/dados_paciente/')

        if request.method == "POST":
            titulo = request.POST.get('titulo')
            horario = request.POST.get('horario')
            carboidratos = request.POST.get('carboidratos')
            proteinas = request.POST.get('proteinas')
            gorduras = request.POST.get('gorduras')

            # TODO: verificar se todos os campos foram preenchidos e validados
            refeicao = Refeicao(paciente=paciente,
                        titulo=titulo,
                        horario=horario,
                        carboidratos=carboidratos,
                        proteinas=proteinas,
                        gorduras=gorduras)

            refeicao.save()

            messages.add_message(request, constants.SUCCESS, 'Refeição cadastrada')
            return redirect(f'/plano_alimentar/{id_paciente}')
        

def opcao(request, id_paciente):
    if request.method == "POST":
        id_refeicao = request.POST.get('refeicao')
        imagem = request.FILES.get('imagem')
        descricao = request.POST.get("descricao")

        opcao = Opcao(refeicao_id=id_refeicao,
                   imagem=imagem,
                   descricao=descricao)

        opcao.save()

        messages.add_message(request, constants.SUCCESS, 'Opção cadastrada')
        return redirect(f'/plano_alimentar/{id_paciente}')
    


## TODO: realizar os procedimentos para exportar o PDF

plataforma/templates/dados_paciente.html
{% extends 'base_plataforma.html' %}
{% load static %}

{% block 'plataforma' %}

    {% if messages %}
        <br>
        {% for message in messages %}
            <div class="alert {{message.tags}}">
                {{message}}
            </div>
        {% endfor %}
    {% endif %}
    <br>

    <div class="row">
        <div class="col-md-3">
            {% if paciente.sexo == "M"%}
                <img src="{% static 'plataforma/img/perfil2.png' %}">
            {% else %}
                <img src="{% static 'plataforma/img/perfil1.png' %}">
            {% endif %}
        </div>

        <div class="col-md-3 dados descricao">
            <h4>{{ paciente.nome }}</h4>
            <h6>{{ paciente.idade }}</h6>
        </div>
        
    </div>
    <hr>


    <button type="button" class="btn btn-outline-success" data-toggle="modal" data-target="#modal">
        Adicionar dados do paciente
    </button>
    <br>
    <br>
    <table class="table table-striped">
        <thead>
            <tr>
            <th scope="col">Peso</th>
            <th scope="col">Altura</th>
            <th scope="col">% Gordura</th>
            <th scope="col">% Músculo</th>
            </tr>
        </thead>
        <tbody>
            {% for dado in dados_paciente %}
                <tr>
                    <th scope="row">{{ dado.peso }} Kg</th>
                    <td>{{ dado.altura }} cm</td>
                    <td>{{ dado.percentual_gordura }} %</td>
                    <td>{{ dado.percentual_musculo }}%</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <div style="width: 80%;">
        <canvas id="myChart"></canvas>
    </div>  

    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script>
        fetch("/grafico_peso/{{ paciente.id }}/",{
            method: 'POST',
        }).then(function(result){
            return result.json()
        }).then(function(data_paciente){        
            const data = {
                labels: data_paciente['labels'],
                datasets: [{
                label: 'Peso paciente',
                backgroundColor: 'rgb(255, 99, 132)',
                borderColor: 'rgb(255, 99, 132)',
                data: data_paciente['peso'],
                }]
            };
            const config = {
                type: 'line',
                data: data,
                options: {}
            };
            const myChart = new Chart(
                document.getElementById('myChart'),
                config
            );
        })
    </script>

    <div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                
                <div class="modal-body">
                    <form action="{% url 'plataforma:dados_paciente' paciente.id %}" method="POST">
                        {% csrf_token %}
                        <h4 class="titulo">Dados do paciente</h4>
                        <div class="form-row">
                            <div class='col-md'>
                            
                                    <label for="validationServerUsername">Peso</label>
                                    <div class="input-group">
                                        <input type="number" class="form-control" placeholder="--" name="peso">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text" id="inputGroupPrepend3">Kg</span>
                                        </div>
                                    </div>
                                                            
                            </div>

                            <div class='col-md'>
                            
                                    <label for="validationServerUsername">Altura</label>
                                    <div class="input-group">
                                        <input type="number" class="form-control" placeholder="--" name="altura">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text" id="inputGroupPrepend3">cm</span>
                                        </div>
                                    </div>
                                                            
                            </div>

                            
                        </div>
                        <br>
                        <div class="form-row">
                            <div class='col-md'>
                            
                                    <label for="validationServerUsername">Percentual de gordura</label>
                                    <div class="input-group">
                                        <input type="number" class="form-control" placeholder="--" name="gordura">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text" id="inputGroupPrepend3">%</span>
                                        </div>
                                    </div>
                                                            
                            </div>

                            <div class='col-md'>
                            
                                    <label for="validationServerUsername">Percentual de músculo</label>
                                    <div class="input-group">
                                        <input type="number" class="form-control" placeholder="--" name="musculo">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text" id="inputGroupPrepend3">%</span>
                                        </div>
                                    </div>
                                                            
                            </div>

                            
                        </div>
                        <br>
                        <h4 class="titulo">Dados laboratoriais</h4>
                        <div class="form-row">
                            <div class='col-md'>
                            
                                    <label for="validationServerUsername">Colesterol HDL</label>
                                    <div class="input-group">
                                        <input type="number" class="form-control" placeholder="--" name="hdl">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text" id="inputGroupPrepend3">mg/dL</span>
                                        </div>
                                    </div>
                                                            
                            </div>

                            <div class='col-md'>
                            
                                    <label for="validationServerUsername">Colesterol LDL</label>
                                    <div class="input-group">
                                        <input type="number" class="form-control" placeholder="--" name="ldl">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text" id="inputGroupPrepend3">mg/dL</span>
                                        </div>
                                    </div>
                                                            
                            </div>

                            
                        </div>
                        <br>
                        <div class="form-row">
                            <div class='col-md'>
                            
                                    <label for="validationServerUsername">Colesterol total</label>
                                    <div class="input-group">
                                        <input type="number" class="form-control" placeholder="--" name="ctotal">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text" id="inputGroupPrepend3">mg/dL</span>
                                        </div>
                                    </div>
                                                            
                            </div>

                            <div class='col-md'>
                            
                                    <label for="validationServerUsername">Triglicerídios</label>
                                    <div class="input-group">
                                        <input type="number" class="form-control" placeholder="--" name="triglicerídios">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text" id="inputGroupPrepend3">mg/dL</span>
                                        </div>
                                    </div>
                                                            
                            </div>

                            
                        </div>

                        <br>

                        <input type="submit" value="Cadastrar" class="btn btn-success">

                    </form>
                </div>
            
            </div>
        </div>
    </div>    
        
{% endblock%}

plataforma/templates/plano_alimentar.html
{% extends 'base_plataforma.html' %}
{% load static %}

{% block 'plataforma' %}
    {% if messages %}
        <br>
        {% for message in messages %}
            <div class="alert {{message.tags}}">
                {{message}}
            </div>
        {% endfor %}
    {% endif %}
    <br>

    <div class="row">

        <div class="col-md-3">
                {% if paciente.sexo == "M"%}
                    <img src="{% static 'plataforma/img/perfil2.png' %}">
                {% else %}
                    <img src="{% static 'plataforma/img/perfil1.png' %}">
                {% endif %}
        </div>

        <div class="col-md-3 dados descricao">
            <h4>{{paciente.nome}}</h4>
            <h6>{{paciente.idade}} Anos</h6>
        </div>
        
    </div>
    <hr>


    <button type="button" class="btn btn-outline-success" data-toggle="modal" data-target="#modal">
        + Nova refeição
    </button>

    <button type="button" class="btn btn-outline-primary">
        Exportar refeição
    </button>
    <br>
    <br>

    <div class="fundo-alimentar">
        {% if refeicoes %}        
            {% for refeicao in refeicoes %}            
                <div class="refeicao">
                    <div class="head-refeicao">
                        <span>{{ refeicao.titulo }}</span>
                        <span style="float: right;">{{ refeicao.horario }} h</span>
                    </div>
                    <div class="body-refeicao">
                        {% for opcao in opcoes %} 
                            {% if opcao.refeicao == refeicao %}
                                <div class="opcao">
                                    <div class="row">
                                        <div class="col-md-2">
                                            <img width="100%" src="{{ opcao.imagem.url }}"> 
                                        </div>
                                        <div class="col-md-10">
                                            {{ opcao.descricao }}
                                        </div>
                                    </div>
                                </div>
                                <br>
                            {% endif %}          
                        {% endfor %}
                    </div>
                </div>
                <br>
            {% endfor %}
        {% else %}
            <div class="row">
                <div class="col-md">
                    <h1 class="titulo">Nenhuma refeição cadastrada</h1>                    
                </div>
                <div>
                    <img width="80%" src="{% static 'plataforma/img/sem_refeicao.jpeg' %}">               
                </div>            
            </div>
        {% endif %}
    </div>



        




    <div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                
                <div class="modal-body">
                    
                        <h4 class="titulo">Adicionar refeição</h4>

                        <button type="button" onclick="exibe_refeicao()" class="btn btn-outline-success">
                            + Nova refeição
                        </button>

                        <button style="margin-left: 10px;" type="button" onclick="exibe_opcao()" class="btn btn-outline-success" >
                            + Nova opção
                        </button>
                        <br>
                        <br>
                        
                        <div id="form-refeicao" style="display: block;">
                            <form action="{% url 'plataforma:refeicao' paciente.id %}" method="POST">
                                {% csrf_token %}
                                <label for="validationServerUsername">Título</label>
                                <div class="input-group">
                                    <input type="text" class="form-control" placeholder="Ex: Café da manhã" name="titulo">
                                </div>
                                <br>
                                <label for="validationServerUsername">Horário</label>
                                <div class="input-group">
                                    <input type="time" class="form-control" placeholder="-" name="horario">
                                </div>
                                <br>
                                <h5 class="titulo">Macronutrientes</h5>
                                <div class="container">
                                    <div class="row">
                                        <div class="col-md-4">
                                            <label for="validationServerUsername">Carboidratos</label>
                                            <div class="input-group">
                                                <input type="text" class="form-control" placeholder="" name="carboidratos">
                                            </div>
                                        </div>

                                        <div class="col-md-4">
                                            <label for="validationServerUsername">Proteínas</label>
                                            <div class="input-group">
                                                <input type="text" class="form-control" placeholder="" name="proteinas">
                                            </div>
                                        </div>

                                        <div class="col-md-4">
                                            <label for="validationServerUsername">Gorduras</label>
                                            <div class="input-group">
                                                <input type="text" class="form-control" placeholder="" name="gorduras">
                                            </div>
                                        </div>

                                    </div>
                                </div>
                                <br>
                                <input type="submit" value="Cadastrar" class="btn btn-success">
                            </form>
                        </div>

                        <div id="form-opcao" style="display: none;">
                        <!-- enctype='multipart/form-data' -> é preciso colocar essa tag no form para poder manipular o envio de arquivos -->
                            <form action="{% url 'plataforma:opcao' paciente.id %}" method="POST" enctype='multipart/form-data'>
                                {% csrf_token %}

                                <label for="validationServerUsername">Selecione a refeição</label>
                                <div class="input-group">
                                    <select class="form-control" name="refeicao">
                                        {% for refeicao in refeicoes %}                                    
                                            <option value="{{ refeicao.id }}">{{ refeicao.titulo}}</option>      
                                        {% endfor %}
                                    </select>
                                </div>

                                <br>

                                <label for="validationServerUsername">Imagem</label>
                                <div class="input-group">
                                    <input type="file" class="form-control" placeholder="Escolha a imagem" name="imagem">
                                </div>
                                
                                <br>

                                <label for="validationServerUsername">Descrição</label>
                                <div class="input-group">
                                    <textarea class="form-control" name='descricao'>

                                    </textarea>
                                </div>
                                <br>
                                <input type="submit" value="Cadastrar" class="btn btn-success">
                            </form>
                        </div>

                       
                        

                    </form>
                </div>
            
            </div>
        </div>
    </div>


    <script>
        function exibe_refeicao(){
            const form_refeicao = document.getElementById('form-refeicao');
            const form_opcao = document.getElementById('form-opcao')

            form_refeicao.style.display = 'block';
            form_opcao.style.display = 'none';
        };
        function exibe_opcao(){
            const form_refeicao = document.getElementById('form-refeicao');
            const form_opcao = document.getElementById('form-opcao');

            form_refeicao.style.display = 'none';
            form_opcao.style.display = 'block';
        }
    </script>   

{% endblock%}