nutrilab/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('autenticacao.urls')),
    path('', include('plataforma.urls')),
]
## Adiciona a URL para os arquivos de media
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

plataforma/urls.py
from django.urls import path
from . import views


app_name = 'plataforma'

urlpatterns = [
    path('pacientes/', views.pacientes, name='pacientes'),
    path('dados_paciente/', views.dados_paciente_listar, name='dados_paciente_listar'),
    path('dados_paciente/<str:id>/', views.dados_paciente, name='dados_paciente'),
    path('grafico_peso/<str:id>/', views.grafico_peso, name='grafico_peso'),
    path('plano_alimentar_listar/', views.plano_alimentar_listar, name='plano_alimentar_listar'),
    path('plano_alimentar/<str:id>', views.plano_alimentar, name='plano_alimentar'),
    path('refeicao/<str:id_paciente>', views.refeicao, name='refeicao'),
    path('opcao/<str:id_paciente>', views.opcao, name='opcao'),
]

templates/base.html
{% load static %}
<!doctype html>
<html lang="pt-BR">
  <head>
    {% block 'head' %}{% endblock  %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">

    <title>{% block 'titulo' %}{% endblock  %}</title>
  </head>
  <body>
    {% if user.is_authenticated %}
        <nav style="background-color: #27DB8F;" class="navbar navbar-expand-lg navbar-dark">
          <a style="font-weight: bold" class="navbar-brand" href="#">NUTRI LAB</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button> 
        </nav>
    {% endif %}  

    {% block 'body' %}
    
    {% endblock  %}

    
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js" ></script>

   
  </body>
</html>

templates/base_plataforma.html
{% extends 'base.html' %}
{% load static  %}

{% block 'head' %}
    <link rel="stylesheet" href="{% static 'plataforma/css/css.css' %}">
    <link rel="stylesheet" href="{% static 'plataforma/css/plano_alimentar.css' %}">
{% endblock %}

{% block 'body' %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-2">
                <a href="{% url 'plataforma:pacientes' %}" class="link-lateral">
                    <div class="card-lateral">
                        <img src="{% static 'plataforma/img/paciente.png' %}">
                        <br>
                        <br>

                        <h3>Gerenciar Pacientes</h3>
                    </div>
                </a>

                <a href="{% url 'plataforma:dados_paciente_listar' %}" class="link-lateral">
                    <div class="card-lateral">
                        <img src="{% static 'plataforma/img/dados_paciente.png' %}">
                        <br>
                        <br>

                        <h3>Dados do Pacientes</h3>
                    </div>
                </a>

                <a href="{% url 'plataforma:plano_alimentar_listar' %}" class="link-lateral">
                    <div class="card-lateral">
                        <img src="{% static 'plataforma/img/plano_alimentar.png' %}">
                        <br>
                        <br>

                        <h3>Plano alimentar</h3>
                    </div>
                </a>

            </div>

            <div class="col-md-8">

                {% block 'plataforma' %}


                {% endblock %}
            </div>

        </div>
    </div>
{% endblock%}